$177647672452701
$177647672452701
$177647672452701
$177647672452701
(de lst-pair-xb-x/ax NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/ax
      '(((+Pair)
            ("c" ("d" "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d" "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" "e")
            x
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647672635751
$177647672635751
$177647672635751
$177647672635751
(de lst-pair-xb-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/nx
      '(((+Pair)
            ("c" (NIL "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (6020510 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "d")
            x
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (4816408 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            NIL )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (7826663 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647672761642
$177647672761642
$177647672761642
$177647673037330
(de lst-pair-xb-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-make-char (char "e"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/aa
      '(((+Pair)
            ("c" ("d" . "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d" . "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" . "e")
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (1204102 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647673101432
$177647673101432
$177647673101432
(de lst-pair-xb-x/an NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/an
      '(((+Pair)
            ("c" ("d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647673175737
$177647673175737
$177647673175737
(de lst-pair-xb-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/nn
      '(((+Pair)
            ("c" (NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647673277777
$177647673277777
$177647673277777
$177647673331472
$177647673356750
(de lst-pair-xb-x/na NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (ver-start
      'lst-pair-xb-x/na
      '(((+Pair)
            ("c" NIL . "d")
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (NIL . "d")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 1204102)
            NIL ) ) ) )

$177647673376747
$177647673376747
$177647673376747
$177647673455152
$177647673455152
(de lst-pair-xb-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/xx
      '(((+Pair)
            ("c" (("d") "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((("d") "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("d") "e")
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647673547651
$177647673547651
$177647673547651
$177647673625465
(de lst-pair-xb-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/xy
      '(((+Pair)
            ("c" (("d") NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((("d") NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("d") NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647673724541
$177647673724541
$177647674005515
$177647674005515
(de lst-pair-xb-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/yx
      '(((+Pair)
            ("c" ((NIL) "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (((NIL) "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) "d")
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -8428714 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -8428714 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674102772
$177647674102772
$177647674102772
$177647674204277
(de lst-pair-xb-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/yy
      '(((+Pair)
            ("c" ((("d")) NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (6020510 14449224)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (((("d")) NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((("d")) NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            (("d"))
            y
            NIL
            T
            NIL
            (6622561 -3612306 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (7826663 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -9632816 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -9632816 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -12041020 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -14449224 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674310006
$177647674310006
$177647674346150
$177647674346150
(de lst-pair-xb-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/nx
      '(((+Pair)
            ("c" (NIL "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 9632816)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674436303
$177647674436303
(de lst-pair-xb-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/nn
      '(((+Pair)
            ("c" (NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674537156
$177647674537156
(de lst-pair-ya-x/ax NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/ax
      '(((+Pair)
            ((("d" "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 6020510)
            (NIL T) )
         ((+Pair)
            (("d" "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 3612306)
            (NIL T) )
         ((+Pair)
            ("d" "c")
            x
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674665741
$177647674665741
(de lst-pair-ya-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/nx
      '(((+Pair)
            (((NIL "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 3612306)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            x
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (9030765 0 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (9030765 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675021253
$177647675021253
$177647675061132
(de lst-pair-ya-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/aa
      '(((+Pair)
            ((("c" . "d")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (("c" . "d"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Pair)
            ("c" . "d")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (1204102 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675146041
$177647675146041
(de lst-pair-ya-x/an NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/an
      '(((+Pair)
            ((("c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            (("c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675252362
$177647675252362
(de lst-pair-ya-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/nn
      '(((+Pair)
            (((NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 3612306)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675365165
$177647675365165
$177647675402073
$177647675426542
(de lst-pair-ya-x/na NIL
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/na
      '(((+Pair)
            (((NIL . "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            (NIL . "c")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675516672
$177647675533625
$177647675540247
$177647675540247
(de lst-pair-ya-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/xx
      '(((+Pair)
            ((((NIL) "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 9632816)
            (NIL T) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 7224612)
            (NIL T) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675712272
$177647675727230
$177647675733652
(de lst-pair-ya-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/xy
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 10836918)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647676111707
$177647676202645
$177647676202645
(de lst-pair-ya-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/yx
      '(((+Pair)
            ((((NIL) "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 10836918)
            (NIL T) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647676302232
$177647676345600
(de lst-pair-ya-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/yy
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 12041020)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647677601433
$177647677035533
$177647677035533
(de lst-pair-ya-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/nx
      '(((+Pair)
            (((NIL "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            y
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647677141136
$177647676276560
(de lst-pair-ya-y/aa NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/aa
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 12041020)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647676427045
(de lst-pair-ya-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/nn
      '(((+Pair)
            (((NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647676137472
$177647676161052
$177647676205144
$177647676205144
(de lst-pair-yb-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/nx
      '(((+Pair)
            (NIL (NIL "e"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675676767
$177647675720347
$177647675720347
$177647675765321
(de lst-pair-yb-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-make-char (char "d"))
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/aa
      '(((+Pair)
            (NIL ("d") . "c")
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("d") . "c")
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (0 0)
            (T NIL) ) ) ) )

$177647676014047
$177647676035427
$177647676035427
(de lst-pair-yb-x/an NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/an
      '(((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            y
            T
            NIL
            NIL
            (5418459 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675522630
$177647675544210
$177647675544210
(de lst-pair-yb-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/nn
      '(((+Pair)
            (NIL (NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675635131
$177647675256110
$177647675256110
(de lst-pair-yb-x/na NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/na
      '(((+Pair)
            (NIL (NIL . "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL . "c")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675351732
$177647675373312
$177647675373312
$177647675437637
$177647675437637
(de lst-pair-yb-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/xx
      '(((+Pair)
            (NIL (("c") "d"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((("c") "d"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("c") "d")
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647675134057
$177647675155434
$177647675155434
$177647675221741
(de lst-pair-yb-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/xy
      '(((+Pair)
            (NIL (("c") NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((("c") NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("c") NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674722104
$177647674743464
$177647675013133
$177647675013133
(de lst-pair-yb-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/yx
      '(((+Pair)
            (NIL ((NIL) "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674511521
$177647674533101
$177647674602550
(de lst-pair-yb-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/yy
      '(((+Pair)
            (NIL ((NIL) NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674305063
$177647674326443
$177647674352537
$177647674352537
(de lst-pair-yb-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/nx
      '(((+Pair)
            (NIL (NIL "e"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

$177647674445002
$177647674065762
(de lst-pair-yb-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/nn
      '(((+Pair)
            (NIL (NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

