(de alt-reg-x-pair-a-a NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-alt-reg)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-x-pair-a-a
      '(((+Pair)
            ("c" . "d")
            x
            T
            T
            NIL
            (4214357 0 0)
            T
            (1204102 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (0 1204102)
            NIL ) ) ) )

(de alt-reg-x-pair-a-px NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-x-pair-a-px
      '(((+Pair)
            (("d") . "c")
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) ) ) ) )

(de alt-reg-x-pair-a-py NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair)
   (cmd-ptr-left)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-x-pair-a-py
      '(((+Pair)
            ((NIL) . "c")
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 2408204)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -4816408 0)
            T
            (0 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-a-a NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-alt-reg)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-a-a
      '(((+Pair)
            ("c" . "d")
            y
            T
            T
            NIL
            (4214357 0 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-a-px NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-a-px
      '(((+Pair)
            (("c"))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -3612306 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-a-py NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-down)
   (cmd-make-pair)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-a-py
      '(((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -4816408 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-px-a NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-left)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-px-a
      '(((+Pair)
            (NIL NIL)
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (4214357 -2408204 0)
            T
            (3612306 1204102)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -3612306 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 1204102)
            NIL ) ) ) )

(de alt-reg-y-pair-py-a NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-make-pair)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-py-a
      '(((+Pair)
            (NIL NIL)
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 4816408)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -4816408 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-px-px NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-px-px
      '(((+Pair)
            (("c") NIL)
            y
            NIL
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (4214357 -3612306 0)
            T
            (3612306 1204102)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -4816408 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 1204102)
            NIL ) ) ) )

(de alt-reg-y-pair-px-py NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-pair)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-px-py
      '(((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (4214357 -4816408 0)
            T
            (3612306 1204102)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL ) ) ) )

(de alt-reg-y-pair-py-py NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-make-pair)
   (cmd-ptr-down)
   (cmd-make-pair)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-py-py
      '(((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (4214357 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de alt-reg-y-pair-py-px NIL
   (cmd-ptr-right)
   (cmd-make-pair)
   (cmd-make-pair)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-alt-reg)
   (ver-start
      'alt-reg-y-pair-py-px
      '(((+Pair)
            (("c") NIL)
            y
            NIL
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

