(de lst-pair-xb-x/ax NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/ax
      '(((+Pair)
            ("c" ("d" "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d" "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" "e")
            x
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/nx
      '(((+Pair)
            ("c" (NIL "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (6020510 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "d")
            x
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (4816408 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            NIL )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (7826663 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-make-char (char "e"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/aa
      '(((+Pair)
            ("c" ("d" . "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d" . "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" . "e")
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (1204102 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-x/an NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/an
      '(((+Pair)
            ("c" ("d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-x/nn
      '(((+Pair)
            ("c" (NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-x/na NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (ver-start
      'lst-pair-xb-x/na
      '(((+Pair)
            ("c" NIL . "d")
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (NIL . "d")
            x
            T
            T
            NIL
            (5418459 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 1204102)
            NIL ) ) ) )

(de lst-pair-xb-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/xx
      '(((+Pair)
            ("c" (("d") "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((("d") "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("d") "e")
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/xy
      '(((+Pair)
            ("c" (("d") NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((("d") NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("d") NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/yx
      '(((+Pair)
            ("c" ((NIL) "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (((NIL) "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) "d")
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -8428714 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -8428714 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-xb-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/yy
      '(((+Pair)
            ("c" ((("d")) NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (6020510 14449224)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (((("d")) NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((("d")) NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            (("d"))
            y
            NIL
            T
            NIL
            (6622561 -3612306 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (7826663 -3612306 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -9632816 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -9632816 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -12041020 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -14449224 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-xb-y/ax NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/ax
      '(((+Pair)
            ("c" ("d" "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 9632816)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d" "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" "e")
            y
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-xb-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/nx
      '(((+Pair)
            ("c" (NIL "e"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 9632816)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -3612306 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-xb-y/aa NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-ptr-right)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/aa
      '(((+Pair)
            ("c" ("e" . "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 8428714)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("e" . "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("e" . "d")
            y
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

#{
(de lst-pair-xb-y/an NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/an
      '(((+Pair)
            ("c" ("d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 8428714)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            (("d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d")
            y
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-xb-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/nn
      '(((+Pair)
            ("c" (NIL))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-xb-y/na NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-xb-y/na
      '(((+Pair)
            ("c" (NIL . "d"))
            x
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ((NIL . "d"))
            y
            NIL
            T
            NIL
            (4214357 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL . "d")
            y
            T
            T
            NIL
            (5418459 -3612306 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-ya-x/ax NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/ax
      '(((+Pair)
            ((("d" "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 6020510)
            (NIL T) )
         ((+Pair)
            (("d" "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 3612306)
            (NIL T) )
         ((+Pair)
            ("d" "c")
            x
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/nx
      '(((+Pair)
            (((NIL "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 3612306)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            x
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (9030765 0 0)
            T
            (0 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (9030765 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-make-char (char "d"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/aa
      '(((+Pair)
            ((("c" . "d")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (("c" . "d"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Pair)
            ("c" . "d")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (1204102 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-x/an NIL
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/an
      '(((+Pair)
            ((("c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            (("c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/nn
      '(((+Pair)
            (((NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 3612306)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-x/na NIL
   (cmd-ptr-right)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-x/na
      '(((+Pair)
            (((NIL . "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 3612306)
            (NIL T) )
         ((+Pair)
            (NIL . "c")
            x
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/xx
      '(((+Pair)
            ((((NIL) "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 9632816)
            (NIL T) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 7224612)
            (NIL T) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/xy
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (7224612 10836918)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (6020510 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (7826663 0 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -1204102 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (10234867 0 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -3612306 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -3612306 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/yx
      '(((+Pair)
            ((((NIL) "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 10836918)
            (NIL T) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/yy
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 12041020)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-ya-y/ax NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/ax
      '(((+Pair)
            ((("c" "d")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            (("c" "d"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("c" "d")
            y
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-ya-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/nx
      '(((+Pair)
            (((NIL "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 8428714)
            (NIL T) )
         ((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            y
            T
            NIL
            NIL
            (6622561 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-ya-y/aa NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/aa
      '(((+Pair)
            ((((NIL) NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (6020510 12041020)
            (NIL T) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (6622561 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (7826663 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (9030765 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -4816408 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-ya-y/an NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/an
      '(((+Pair)
            ((("c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (("c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (2408204 4816408)
            (NIL T) )
         ((+Pair)
            ("c")
            y
            T
            T
            NIL
            (6622561 0 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-ya-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/nn
      '(((+Pair)
            (((NIL)))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-ya-y/na NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-ya-y/na
      '(((+Pair)
            (((NIL . "c")))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (4816408 7224612)
            (NIL T) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (5418459 0 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            (NIL . "c")
            y
            T
            T
            NIL
            (6622561 0 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

            
(de lst-pair-yb-x/ax NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/ax
      '(((+Pair)
            (NIL ("c" "d"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("c" "d"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("c" "d")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-yb-x/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/nx
      '(((+Pair)
            (NIL (NIL "e"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-x/aa NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-make-char (char "d"))
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/aa
      '(((+Pair)
            (NIL ("d") . "c")
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("d") . "c")
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (0 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-x/an NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/an
      '(((+Pair)
            ((NIL "c"))
            y
            NIL
            T
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL "c")
            y
            T
            NIL
            NIL
            (5418459 0 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-x/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-nil)
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/nn
      '(((+Pair)
            (NIL (NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (3612306 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-x/na NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-x/na
      '(((+Pair)
            (NIL (NIL . "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL . "c")
            x
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -3612306 0)
            T
            (1204102 0)
            NIL )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (0 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -6020510 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-y/xx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/xx
      '(((+Pair)
            (NIL (("c") "d"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 9632816)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((("c") "d"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("c") "d")
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 4816408)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            ("d")
            x
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (5418459 -7224612 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -9632816 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-y/xy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/xy
      '(((+Pair)
            (NIL (("c") NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((("c") NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (("c") NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 1204102)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -3612306 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 1204102)
            NIL )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -6020510 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -6020510 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-y/yx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/yx
      '(((+Pair)
            (NIL ((NIL) "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 10836918)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (((NIL) "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) "c")
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 6020510)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            ("c")
            x
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -8428714 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -10836918 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

(de lst-pair-yb-y/yy NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/yy
      '(((+Pair)
            (NIL ((NIL) NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (4816408 12041020)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (((NIL) NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ((NIL) NIL)
            y
            NIL
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (6622561 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (7826663 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -7224612 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -7224612 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -9632816 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -12041020 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-yb-y/ax NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/ax
      '(((+Pair)
            (NIL ("d" "e"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("d" "e"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" "e")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-yb-y/nx NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-char (char "e"))
   (cmd-ptr-left)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/nx
      '(((+Pair)
            (NIL (NIL "e"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 8428714)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL "e"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL "e")
            y
            T
            NIL
            NIL
            (5418459 -2408204 0)
            T
            (2408204 3612306)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ("e")
            x
            T
            T
            NIL
            (5418459 -4816408 0)
            T
            (2408204 1204102)
            (T NIL) )
         ((+Str)
            "e"
            x
            NIL
            NIL
            T
            (5418459 -6020510 0)
            T
            (0 0)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -4816408 0)
            T
            (1204102 1204102)
            NIL )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -8428714 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-yb-y/aa NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-ptr-right)
   (cmd-make-char (char "d"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/aa
      '(((+Pair)
            (NIL ("d" . "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 7224612)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("d" . "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("d" . "c")
            y
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "d"
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )


(de lst-pair-yb-y/an NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-ptr-left)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/an
      '(((+Pair)
            (NIL ("c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (2408204 7224612)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            (("c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            ("c")
            y
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (1204102 2408204)
            (NIL T) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (0 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#

(de lst-pair-yb-y/nn NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/nn
      '(((+Pair)
            (NIL (NIL))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL)
            y
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (1204102 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )

#{
(de lst-pair-yb-y/na NIL
   (cmd-ptr-right)
   (cmd-make-pair-y)
   (cmd-ptr-down)
   (cmd-make-pair-y)
   (cmd-ptr-right)
   (cmd-make-char (char "c"))
   (cmd-alt-reg)
   (cmd-ptr-up)
   (cmd-make-pair-y)
   (ver-start
      'lst-pair-yb-y/na
      '(((+Pair)
            (NIL (NIL . "c"))
            y
            T
            NIL
            NIL
            (4214357 0 0)
            T
            (3612306 7224612)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (5418459 0 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Pair)
            ((NIL . "c"))
            y
            NIL
            T
            NIL
            (4214357 -2408204 0)
            T
            (0 0)
            (T NIL) )
         ((+Pair)
            (NIL . "c")
            y
            T
            T
            NIL
            (5418459 -2408204 0)
            T
            (2408204 2408204)
            (NIL T) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (6622561 -2408204 0)
            T
            (1204102 0)
            (NIL NIL) )
         ((+Str)
            "c"
            x
            NIL
            NIL
            T
            (5418459 -4816408 0)
            T
            (0 0)
            (T NIL) )
         ((+Nil)
            NIL
            x
            NIL
            NIL
            T
            (4214357 -7224612 0)
            T
            (1204102 0)
            (T NIL) ) ) ) )
}#
